from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QGraphicsDropShadowEffect, QPushButton, QApplication, QComboBox
import sys

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 761, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_pump1 = QtWidgets.QPushButton(self.frame)
        self.btn_pump1.setGeometry(QtCore.QRect(540, 10, 221, 51))
        self.btn_pump1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_pump1.setObjectName("btn_pump1")
        self.btn_pump3 = QtWidgets.QPushButton(self.frame)
        self.btn_pump3.setGeometry(QtCore.QRect(540, 130, 221, 51))
        self.btn_pump3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_pump3.setObjectName("btn_pump3")
        self.frame_output = QtWidgets.QFrame(self.frame)
        self.frame_output.setGeometry(QtCore.QRect(0, 0, 511, 361))
        self.frame_output.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.frame_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_output.setObjectName("frame_output")
        self.label_10 = QtWidgets.QLabel(self.frame_output)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 231, 31))
        self.label_10.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.txt_output = QtWidgets.QPlainTextEdit(self.frame_output)
        self.txt_output.setGeometry(QtCore.QRect(20, 40, 471, 171))
        self.txt_output.setObjectName("txt_output")
        self.label_2 = QtWidgets.QLabel(self.frame_output)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 41, 16))
        self.label_2.setObjectName("label_2")
        self.lbl_ticks = QtWidgets.QLabel(self.frame_output)
        self.lbl_ticks.setGeometry(QtCore.QRect(70, 300, 181, 16))
        self.lbl_ticks.setObjectName("lbl_ticks")
        self.label_4 = QtWidgets.QLabel(self.frame_output)
        self.label_4.setGeometry(QtCore.QRect(20, 300, 51, 16))
        self.label_4.setObjectName("label_4")
        self.lbl_time = QtWidgets.QLabel(self.frame_output)
        self.lbl_time.setGeometry(QtCore.QRect(80, 240, 171, 16))
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_hertz = QtWidgets.QLabel(self.frame_output)
        self.lbl_hertz.setGeometry(QtCore.QRect(70, 270, 181, 16))
        self.lbl_hertz.setObjectName("lbl_hertz")
        self.label_3 = QtWidgets.QLabel(self.frame_output)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 41, 16))
        self.label_3.setObjectName("label_3")
        self.lbl = QtWidgets.QLabel(self.frame_output)
        self.lbl.setGeometry(QtCore.QRect(260, 240, 71, 21))
        self.lbl.setObjectName("lbl")
        self.lbl_msg = QtWidgets.QLabel(self.frame_output)
        self.lbl_msg.setGeometry(QtCore.QRect(260, 270, 191, 21))
        self.lbl_msg.setObjectName("lbl_msg")
        self.lbl_error = QtWidgets.QLabel(self.frame_output)
        self.lbl_error.setGeometry(QtCore.QRect(260, 330, 191, 16))
        self.lbl_error.setObjectName("lbl_error")
        self.label_6 = QtWidgets.QLabel(self.frame_output)
        self.label_6.setGeometry(QtCore.QRect(260, 310, 71, 16))
        self.label_6.setObjectName("label_6")
        self.btn_back = QtWidgets.QPushButton(self.frame)
        self.btn_back.setGeometry(QtCore.QRect(540, 310, 221, 61))
        self.btn_back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_back.setObjectName("btn_back")
        self.btn_calibrate = QtWidgets.QPushButton(self.frame)
        self.btn_calibrate.setGeometry(QtCore.QRect(540, 240, 221, 61))
        self.btn_calibrate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_calibrate.setObjectName("btn_calibrate")
        self.btn_pump2 = QtWidgets.QPushButton(self.frame)
        self.btn_pump2.setGeometry(QtCore.QRect(540, 70, 221, 51))
        self.btn_pump2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_pump2.setObjectName("btn_pump2")
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowFlags(Qt.SplashScreen | Qt.FramelessWindowHint)
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_pump1.setText(_translate("MainWindow", "PUMP1"))
        self.btn_pump3.setText(_translate("MainWindow", "PUMP3"))
        self.label_10.setText(_translate("MainWindow", "Calibration Test"))
        self.label_2.setText(_translate("MainWindow", "Time"))
        self.lbl_ticks.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "TICKS"))
        self.lbl_time.setText(_translate("MainWindow", "00:00"))
        self.lbl_hertz.setText(_translate("MainWindow", "0 Hz"))
        self.label_3.setText(_translate("MainWindow", "Hertz"))
        self.lbl.setText(_translate("MainWindow", "Message :"))
        self.lbl_msg.setText(_translate("MainWindow", "NO message"))
        self.lbl_error.setText(_translate("MainWindow", "No Error"))
        self.label_6.setText(_translate("MainWindow", "ERROR :"))
        self.btn_back.setText(_translate("MainWindow", "BACK "))
        self.btn_calibrate.setText(_translate("MainWindow", "Calibrate Each Motor"))
        self.btn_pump2.setText(_translate("MainWindow", "PUMP2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
