from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QGraphicsDropShadowEffect, QPushButton, QApplication, QComboBox
import sys


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_s3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_s3.setGeometry(QtCore.QRect(20, 30, 751, 371))
        self.frame_s3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_s3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_s3.setObjectName("frame_s3")
        self.frame_s3_setting = QtWidgets.QFrame(self.frame_s3)
        self.frame_s3_setting.setGeometry(QtCore.QRect(0, 0, 751, 361))
        self.frame_s3_setting.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.frame_s3_setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_s3_setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_s3_setting.setObjectName("frame_s3_setting")
        self.label_11 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_12.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox = QtWidgets.QComboBox(self.frame_s3_setting)
        self.comboBox.setGeometry(QtCore.QRect(590, 50, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_16 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_16.setGeometry(QtCore.QRect(480, 10, 261, 31))
        self.label_16.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.btn_save = QtWidgets.QPushButton(self.frame_s3_setting)
        self.btn_save.setGeometry(QtCore.QRect(590, 220, 151, 41))
        self.btn_save.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_save.setObjectName("btn_save")
        self.lblOzhigh = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblOzhigh.setGeometry(QtCore.QRect(240, 50, 61, 16))
        self.lblOzhigh.setObjectName("lblOzhigh")
        self.btn_back = QtWidgets.QPushButton(self.frame_s3_setting)
        self.btn_back.setGeometry(QtCore.QRect(590, 270, 151, 41))
        self.btn_back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(34, 153, 129, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_back.setObjectName("btn_back")
        self.label_23 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.label_23.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.txt_output = QtWidgets.QPlainTextEdit(self.frame_s3_setting)
        self.txt_output.setGeometry(QtCore.QRect(590, 120, 151, 91))
        self.txt_output.setObjectName("txt_output")
        self.label_26 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_26.setGeometry(QtCore.QRect(590, 90, 151, 31))
        self.label_26.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.sliderOnceHigh = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderOnceHigh.setGeometry(QtCore.QRect(60, 50, 171, 22))
        self.sliderOnceHigh.setMaximum(1000)
        self.sliderOnceHigh.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOnceHigh.setObjectName("sliderOnceHigh")
        self.sliderOnceMid = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderOnceMid.setGeometry(QtCore.QRect(60, 90, 171, 22))
        self.sliderOnceMid.setMaximum(1000)
        self.sliderOnceMid.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOnceMid.setObjectName("sliderOnceMid")
        self.sliderOnceLow = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderOnceLow.setGeometry(QtCore.QRect(60, 130, 171, 22))
        self.sliderOnceLow.setMaximum(1000)
        self.sliderOnceLow.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOnceLow.setObjectName("sliderOnceLow")
        self.lblOzMid = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblOzMid.setGeometry(QtCore.QRect(240, 90, 61, 16))
        self.lblOzMid.setObjectName("lblOzMid")
        self.lblOzLow = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblOzLow.setGeometry(QtCore.QRect(240, 130, 61, 16))
        self.lblOzLow.setObjectName("lblOzLow")
        self.label_24 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_24.setGeometry(QtCore.QRect(10, 160, 151, 31))
        self.label_24.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.label_14 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_14.setGeometry(QtCore.QRect(10, 240, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_15.setGeometry(QtCore.QRect(10, 200, 41, 16))
        self.label_15.setObjectName("label_15")
        self.lblGallonHigh = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblGallonHigh.setGeometry(QtCore.QRect(240, 200, 61, 16))
        self.lblGallonHigh.setObjectName("lblGallonHigh")
        self.sliderGallonMid = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderGallonMid.setGeometry(QtCore.QRect(60, 240, 171, 22))
        self.sliderGallonMid.setMaximum(1000)
        self.sliderGallonMid.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGallonMid.setObjectName("sliderGallonMid")
        self.lblGallonLow = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblGallonLow.setGeometry(QtCore.QRect(240, 280, 61, 16))
        self.lblGallonLow.setObjectName("lblGallonLow")
        self.sliderGallonLow = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderGallonLow.setGeometry(QtCore.QRect(60, 280, 171, 22))
        self.sliderGallonLow.setMaximum(1000)
        self.sliderGallonLow.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGallonLow.setObjectName("sliderGallonLow")
        self.sliderGallonHigh = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderGallonHigh.setGeometry(QtCore.QRect(60, 200, 171, 22))
        self.sliderGallonHigh.setMaximum(1000)
        self.sliderGallonHigh.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGallonHigh.setObjectName("sliderGallonHigh")
        self.label_22 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_22.setGeometry(QtCore.QRect(10, 280, 41, 16))
        self.label_22.setObjectName("label_22")
        self.lblGallonMid = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblGallonMid.setGeometry(QtCore.QRect(240, 240, 61, 16))
        self.lblGallonMid.setObjectName("lblGallonMid")
        self.label_27 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_27.setGeometry(QtCore.QRect(290, 10, 151, 31))
        self.label_27.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_28.setGeometry(QtCore.QRect(290, 90, 31, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_29.setGeometry(QtCore.QRect(290, 50, 41, 16))
        self.label_29.setObjectName("label_29")
        self.lblLitreHigh = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblLitreHigh.setGeometry(QtCore.QRect(520, 50, 61, 16))
        self.lblLitreHigh.setObjectName("lblLitreHigh")
        self.sliderLitreMid = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderLitreMid.setGeometry(QtCore.QRect(340, 90, 171, 22))
        self.sliderLitreMid.setMaximum(1000)
        self.sliderLitreMid.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLitreMid.setObjectName("sliderLitreMid")
        self.lblLitreLow = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblLitreLow.setGeometry(QtCore.QRect(520, 130, 61, 16))
        self.lblLitreLow.setObjectName("lblLitreLow")
        self.sliderLitreLow = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderLitreLow.setGeometry(QtCore.QRect(340, 130, 171, 22))
        self.sliderLitreLow.setMaximum(1000)
        self.sliderLitreLow.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLitreLow.setObjectName("sliderLitreLow")
        self.sliderLitreHigh = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderLitreHigh.setGeometry(QtCore.QRect(340, 50, 171, 22))
        self.sliderLitreHigh.setMaximum(1000)
        self.sliderLitreHigh.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLitreHigh.setObjectName("sliderLitreHigh")
        self.label_32 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_32.setGeometry(QtCore.QRect(290, 130, 41, 16))
        self.label_32.setObjectName("label_32")
        self.lblLitreMid = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblLitreMid.setGeometry(QtCore.QRect(520, 90, 61, 16))
        self.lblLitreMid.setObjectName("lblLitreMid")
        self.lbl1oz = QtWidgets.QLabel(self.frame_s3_setting)
        self.lbl1oz.setGeometry(QtCore.QRect(520, 240, 61, 16))
        self.lbl1oz.setObjectName("lbl1oz")
        self.label_58 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_58.setGeometry(QtCore.QRect(300, 280, 61, 16))
        self.label_58.setObjectName("label_58")
        self.sliderMinHz = QtWidgets.QSlider(self.frame_s3_setting)
        self.sliderMinHz.setGeometry(QtCore.QRect(360, 280, 151, 22))
        self.sliderMinHz.setMaximum(100)
        self.sliderMinHz.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinHz.setObjectName("sliderMinHz")
        self.lblMinHz = QtWidgets.QLabel(self.frame_s3_setting)
        self.lblMinHz.setGeometry(QtCore.QRect(520, 280, 61, 16))
        self.lblMinHz.setObjectName("lblMinHz")
        self.label_60 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_60.setGeometry(QtCore.QRect(300, 240, 61, 16))
        self.label_60.setObjectName("label_60")
        self.slider1oz = QtWidgets.QSlider(self.frame_s3_setting)
        self.slider1oz.setGeometry(QtCore.QRect(360, 240, 151, 22))
        self.slider1oz.setMaximum(100)
        self.slider1oz.setOrientation(QtCore.Qt.Horizontal)
        self.slider1oz.setObjectName("slider1oz")
        self.label_61 = QtWidgets.QLabel(self.frame_s3_setting)
        self.label_61.setGeometry(QtCore.QRect(370, 190, 151, 31))
        self.label_61.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_61.setObjectName("label_61")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 0, 231, 31))
        self.label_10.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowFlags(Qt.SplashScreen | Qt.FramelessWindowHint)
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "HIGH"))
        self.label_12.setText(_translate("MainWindow", "MID"))
        self.label_13.setText(_translate("MainWindow", "LOW"))
        self.label_16.setText(_translate("MainWindow", "Select The Pump To calibrate"))
        self.btn_save.setText(_translate("MainWindow", "SAVE"))
        self.lblOzhigh.setText(_translate("MainWindow", "0"))
        self.btn_back.setText(_translate("MainWindow", "BACK"))
        self.label_23.setText(_translate("MainWindow", "OUNCE"))
        self.label_26.setText(_translate("MainWindow", "MESSAGE BOX"))
        self.lblOzMid.setText(_translate("MainWindow", "0"))
        self.lblOzLow.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "GALLON"))
        self.label_14.setText(_translate("MainWindow", "MID"))
        self.label_15.setText(_translate("MainWindow", "HIGH"))
        self.lblGallonHigh.setText(_translate("MainWindow", "0"))
        self.lblGallonLow.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "LOW"))
        self.lblGallonMid.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "LITRE"))
        self.label_28.setText(_translate("MainWindow", "MID"))
        self.label_29.setText(_translate("MainWindow", "HIGH"))
        self.lblLitreHigh.setText(_translate("MainWindow", "0"))
        self.lblLitreLow.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "LOW"))
        self.lblLitreMid.setText(_translate("MainWindow", "0"))
        self.lbl1oz.setText(_translate("MainWindow", "0"))
        self.label_58.setText(_translate("MainWindow", "Min Hz"))
        self.lblMinHz.setText(_translate("MainWindow", "0"))
        self.label_60.setText(_translate("MainWindow", "1 OZ"))
        self.label_61.setText(_translate("MainWindow", "UNIT VALUE"))
        self.label_10.setText(_translate("MainWindow", "Calibration Area"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
